### ISSUE TITLE
debug on serversocket.recv(19)

### ISSUE THREAD

**Issue by pwnslinger** [DiabloHorn/rdps2rdp#1]
python rdps2rdp_pcap.py 
waiting for connection...
('...connected from:', ('192.168.104.240', 9811))
waiting for connection...
Unhandled exception in thread started by <function handler at 0x7fe713018500>
Traceback (most recent call last):
  File "rdps2rdp_pcap.py", line 60, in handler
    temp = serversock.recv(19)
socket.error: [Errno 104] Connection reset by peer

target rdp server is win server 2012 r2 and victim is win 8.

**Comment by DiabloHorn** [comment]
if the version of RDP is to new it won't work.

On Sat, Jun 18, 2016 at 3:13 PM, pwnslinger notifications@github.com
wrote:

> python rdps2rdp_pcap.py
> waiting for connection...
> ('...connected from:', ('192.168.104.240', 9811))
> waiting for connection...
> Unhandled exception in thread started by
> Traceback (most recent call last):
> File "rdps2rdp_pcap.py", line 60, in handler
> temp = serversock.recv(19)
> socket.error: [Errno 104] Connection reset by peer
> 
> target rdp server is win server 2012 r2 and victim is win 8.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DiabloHorn/rdps2rdp/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AAfQ7WJ1vo8Ah0CLrb7OcB1ujFSFq9XJks5qNENhgaJpZM4I5A37
> .

## 

---Just enjoying the journey---
http://diablohorn.wordpress.com
